server:
  port: 8765

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

spring:
  application:
      name: flyray-gateway-v2
  redis:  
      #数据库索引  
      database: 0  
      host: 127.0.0.1  
      port: 6379  
      password:  
      jedis:  
        pool:  
          #最大连接数  
          max-active: 8  
          #最大阻塞等待时间(负数表示没限制)  
          max-wait: -1  
          #最大空闲  
          max-idle: 8  
          #最小空闲  
          min-idle: 0  
      #连接超时时间  
      timeout: 10000  
        
  rabbitmq:
      host: 127.0.0.1
      port:  5672
      username: guest
      password: guest
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # =====================================
      - id: flyray-auth
        uri: lb://flyray-auth
        order: 8000
        predicates:
        - Path=/api/auth/**
        filters:
        - StripPrefix=2
      - id: flyray-admin
        uri: lb://flyray-admin
        order: 8001
        predicates:
        - Path=/api/admin/**
        filters:
        - StripPrefix=2
      - id: flyray-biz
        uri: lb://flyray-biz
        order: 8002
        predicates:
        - Path=/api/biz/**
        filters:
        - StripPrefix=2
      - id: flyray-crm-core
        uri: lb://flyray-crm-core
        order: 8003
        predicates:
        - Path=/api/crm/**
        filters:
        - StripPrefix=2
      - id: flyray-pay-core
        uri: lb://flyray-pay-core
        order: 8004
        predicates:
        - Path=/api/backpay/**
        filters:
        - StripPrefix=2
      - id: flyray-crm-core2
        uri: lb://flyray-crm-core
        order: 8005
        predicates:
        - Path=/api/backcrm/**
        filters:
        - StripPrefix=2
      - id: flyray-biz2
        uri: lb://flyray-biz
        order: 8006
        predicates:
        - Path=/api/backbiz/**
        filters:
        - StripPrefix=2              
    zipkin:
      base-url: http://localhost:9411
logging:
  level:
    com.github.wxiaoqi.security.gate.v2: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false


gate:
  ignore:
    startWith: /auth/jwt,/admin/user/front/info,/admin/user/front/menus,/admin/user/front/menu/all,/crm/customers/userRegister,/crm/smsGateWay/sendSMSCode,/crm/imgCode/getImgCode,/biz/bhIndustry/queryAllIndustry,/biz/bhFunction/queryAllFunction,/biz/bhTask/queryHotPosition,/biz/bhIndustry/queryHotIndustry,/biz/bhFunction/queryHotFunction,/biz/bounty/rewardRecord,/biz/bounty/leaderboard,/biz/bhTask/queryTaskPage
  crm:
    startWith: /crm
  biz:
    startWith: /biz
  

auth:
  serviceId: flyray-auth
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    id: flyray-gate  #不填则默认读取spring.application.name
    secret: 123456
    